FROM openjdk:8-jre

ENTRYPOINT ["/usr/local/openjdk-8/bin/java","-Dmy.hello.log.root=/logs","-jar","/usr/local/javapkg/spring-boot-api-talk-to-db-0.0.1-SNAPSHOT.jar]
ADD target/lib /usr/local/javapkg/lib/
ADD target/spring-boot-api-talk-to-db-0.0.1-SNAPSHOT.jar /usr/local/javapkg/spring-boot-api-talk-to-db-0.0.1-SNAPSHOT.jar
EXPOSE 5000

