server:
  port: 5000

spring:
  application:
    name: spring-boot-api-talk-to-db-service

  batch.job.enabled: false
  datasource:
    url: jdbc:postgresql://ecs-deployment-db.c2kfui9bmsnq.us-east-1.rds.amazonaws.com:5432/ecsdeploymentdb
    username: ecsdeploymentdb
    password: ecs-deployment-db
    driver-class-name: org.postgresql.Driver